default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: joel
  port: 5432

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budget_database

 
test:
  <<: *default
  database: Budget_database_test

production:
  <<: *default
  database: Budget_production
  username: Budget
  password: joel